name: unit test action

on: [push, pull_request]

jobs:
 build:
  runs-on: ubuntu-latest
  steps: 
   - name: checkout repo content
     uses: actions/checkout@v2
   - name: setup python
     uses: actions/setup-python@v2
     with:
       python-version: 3.8.5
   - name: install dependencies
     run: |
       python -m pip install --upgrade pip
       pip install -r requirements.txt
       pip install pytest  
       pip install -e . 
   - name: show pakage is importable
     run: |        
        python -c "import financepy as fp"
   - name: list dependencies
     run: |        
        pip list
   - name: unit tests
     run: |        
        pytest
