name: test_action

on: [push, pull_request]

jobs:
 build:
  runs-on: ubuntu-latest
  steps: 
   - name: checkout repo content
     uses: actions/checkout@v2
   - name: setup python
     uses: actions/setup-python@v2
     with:
       python-version: 3.7.6
   - name: run test script
     run: |
       pip install -r requirements.txt
       python setup.py install
       python tests_golden/runAllTests.py
   - name: Archive code coverage results
     uses: actions/upload-artifact@v2
     with:
        name: result-differences-file-upload
        path: tests_golden/differences/*.testLog

